CREATE TABLE book( book_id SERIAL, name VARCHAR(60) NOT NULL DEFAULT '', genre VARCHAR(60) NOT NULL DEFAULT '', quantity_in_stock INT DEFAULT 0, PRIMARY KEY (book_id) ) WITH( OIDS=FALSE);
CREATE UNIQUE INDEX book_name ON book (name);
CREATE INDEX genre_name ON book (genre);
CREATE TABLE autor( autor_id SERIAL, first_name VARCHAR(60) NOT NULL DEFAULT '', second_name VARCHAR(60) NOT NULL DEFAULT '', middle_name VARCHAR(60) NOT NULL DEFAULT '', full_name VARCHAR(60) NOT NULL DEFAULT '', PRIMARY KEY (autor_id)) WITH( OIDS=FALSE);
CREATE UNIQUE INDEX autor_name ON autor (full_name);
CREATE TABLE book_autor( book_id INT NOT NULL, autor_id INT NOT NULL, FOREIGN KEY (autor_id) REFERENCES autor(autor_id), FOREIGN KEY (book_id) REFERENCES book(book_id) ) WITH( OIDS=FALSE);
CREATE TABLE client( client_id SERIAL,first_name VARCHAR(60) NOT NULL DEFAULT '', second_name VARCHAR(60) NOT NULL DEFAULT '', email VARCHAR(60) NOT NULL DEFAULT '', phone_number VARCHAR(60) NOT NULL DEFAULT '', delivery_address VARCHAR(120) NOT NULL DEFAULT '', PRIMARY KEY (client_id) ) WITH( OIDS=FALSE);
CREATE TABLE rating( book_id INT NOT NULL, rating NUMERIC NOT NULL DEFAULT 0.00, count_voted INT NOT NULL DEFAULT 0, FOREIGN KEY (book_id) REFERENCES book(book_id) ) WITH( OIDS=FALSE);
CREATE TABLE time_of_orders( order_id SERIAL, client_id INT NOT NULL, open_date timestamp with time zone NOT NULL, close_date timestamp with time zone DEFAULT '3000-01-01 00:00:00', FOREIGN KEY (client_id) REFERENCES client(client_id), PRIMARY KEY (order_id), CHECK (open_date < close_date ) ) WITH( OIDS=FALSE);
CREATE TABLE order_items( order_id INT NOT NULL, book_id INT NOT NULL, FOREIGN KEY (order_id) REFERENCES time_of_orders(order_id), FOREIGN KEY (book_id) REFERENCES book(book_id) ) WITH( OIDS=FALSE);
